poshapke/basket/urls.py
from django.urls import path

from basket.views import basket_add, basket_remove

app_name = 'basket'

urlpatterns = [
    path('add/<str:slug>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

poshapke/orders/urls.py
from django.urls import path

from orders.views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('orders_create/', OrderCreateView.as_view(), name='orders_create'),
]

poshapke/poshapke/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

admin.site.site_header = 'Панель Администратора Магазина'
admin.site.index_title = 'Создание и удаление данных'

poshapke/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (
    EmailVerificationView,
    UserLoginView,
    UserProfileView,
    UserRegistrationView,
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path(
        'profile/<str:username>/',
        login_required(UserProfileView.as_view()),
        name='profile',
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'verification/<str:email>/<uuid:url_uuid>/',
        EmailVerificationView.as_view(),
        name='email_verification',
    ),
]

poshapke/basket/models.py
from django.db import models

from products.models import BasketQuerySet, Products
from users.models import Users


class Basket(models.Model):
    user = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE,
        verbose_name='Покупатель'
    )
    product = models.ForeignKey(
        to=Products,
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    quantity = models.PositiveSmallIntegerField(
        default=0,
        verbose_name='Количество товаров в Корзине'
    )
    time_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Время добавления в Корзину'
    )

    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'
        ordering = ('time_create',)

    def __str__(self):
        return f'{self.user} {self.product}'

    def sum_basket(self):
        return self.product.price * self.quantity

poshapke/basket/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from basket.models import Basket
from products.models import Products


@login_required
def basket_add(request, slug):
    user = request.user
    product = get_object_or_404(Products, slug=slug)
    baskets = Basket.objects.filter(user=user, product=product)
    if not baskets.exists():
        Basket.objects.create(user=user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, basket_id):
    basket = get_object_or_404(Basket, id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

poshapke/basket/templates/basket/basket.html
{% if baskets %}
 <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
            </h4>
     {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum_basket }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
     {% endfor %}
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ baskets.total_sum }} руб.</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:orders_create' %}">
                Оформить заказ
            </a>
        </div>
    </div>
</div>
{% else %}
    <div class="col-lg-5 text-center">
        <h4 class="mt-3 mb-3">Корзина пуста</h4>
    </div>
{% endif %}