poshapke/poshapke/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('', include('products.urls', namespace='products')),
    path('', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

admin.site.site_header = 'Панель Администратора Магазина'
admin.site.index_title = 'Создание и удаление данных'

poshapke/products/urls.py
from django.urls import include, path

from products.views import ProductsListView

app_name = 'products'

urlpatterns = [
    path('products/', ProductsListView.as_view(), name='index'),
    path('products/<str:slug>', ProductsListView.as_view(), name='category'),
    path('products/', include('basket.urls', namespace='basket'))
]

poshapke/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (
    EmailVerificationView,
    UserLoginView,
    UserProfileView,
    UserRegistrationView,
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path(
        'profile/<str:username>/',
        login_required(UserProfileView.as_view()),
        name='profile',
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'verification/<str:email>/<uuid:url_uuid>/',
        EmailVerificationView.as_view(),
        name='email_verification',
    ),
]

poshapke/products/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(
        max_length=128,
        unique=True,
        help_text='Введите название Категории',
        verbose_name='Категория',
    )
    slug = models.CharField(
        max_length=128,
        unique=True,
        help_text='URL Категории',
        verbose_name='URL Категории',
    )
    description = models.TextField(
        max_length=256,
        help_text='Опишите Категорию',
        blank=False,
        verbose_name='Описание Категории',
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Products(models.Model):

    name = models.CharField(
        max_length=128, help_text='Название Товара', verbose_name='Имя Товара'
    )
    slug = models.CharField(
        max_length=128, verbose_name='URL Продукта', unique=True
    )
    description = models.TextField(
        max_length=256,
        help_text='Опишите Товар',
        verbose_name='Описание Товара',
    )
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        help_text='Введите Цену Товара',
        verbose_name='Цена',
    )
    quantity = models.PositiveIntegerField(
        default=0,
        help_text='Введите Количество Товара',
        verbose_name='Количество Товара',
    )
    image = models.ImageField(
        upload_to='product_image',
        help_text='Загрузите Фото',
        verbose_name='Фото Товара',
    )
    time_create = models.DateTimeField(
        auto_now_add=True, verbose_name='Время Создания'
    )
    time_update = models.DateTimeField(
        auto_now=True, verbose_name='Время обновления'
    )
    is_published = models.BooleanField(
        default=False, verbose_name='Видимость Товара'
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.PROTECT,
        verbose_name='Категория Товара',
        related_name='category',
    )

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('time_update',)

    def __str__(self):
        return self.name


class BasketQuerySet(models.QuerySet):

    def total_sum(self):
        return sum(basket.sum_basket() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

poshapke/products/views.py
from django.views.generic import ListView, TemplateView

from common.mixins import TitleMixin
from products.models import Category, Products


class IndexView(TitleMixin, TemplateView):
    """
    Главная Страница.
    """
    template_name = 'products/index.html'
    title = 'Главная Страница'


class ProductsListView(TitleMixin, ListView):
    """
    Раздел с Товаром.
    """
    model = Products
    template_name = 'products/products.html'
    paginate_by = 3
    title = 'Каталог'

    def get_queryset(self):
        product = super(ProductsListView, self).get_queryset()
        slug = self.kwargs.get('slug')
        return product.filter(category__slug=slug) if slug else product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context

poshapke/products/templates/products/base.html
{% load static  %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %} {% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Каждому по шапке</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                   <a class="nav-link" href="{% url 'users:profile' user.username %}">{{ user.username }} </a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.username %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                        {% if user.is_superuser or user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

poshapke/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static  %}


{% block css %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5" style="color: #ffffff;">По шапке</h1>
                <p style="color: #ffffff;">
                    Новые образы и лучшие бренды на poshapke.ru.
                    Бесплатная доставка по всему миру! Аутлет: до -70%
                    Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button"
                        class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>

{% endblock %}

poshapke/products/templates/products/products.html
{% extends 'products/base.html' %}

{% load static  %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                <a href="{% url 'products:index' %}" class="list-group-item">Все категории</a>
                {% for cat in categories %}
                <a href="{% url 'products:category' cat.slug %}" class="list-group-item">{{ cat.name }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4"
                 data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators"
                        data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators"
                        data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators"
                        data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid"
                             src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                             alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid"
                             src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                             alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid"
                             src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                             alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev"
                   href="#carouselExampleIndicators" role="button"
                   data-slide="prev">
                    <span class="carousel-control-prev-icon"
                          aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next"
                   href="#carouselExampleIndicators" role="button"
                   data-slide="next">
                    <span class="carousel-control-next-icon"
                          aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in object_list %}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} руб.</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket:basket_add' product.slug %}">
                                Отправить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                href="?page={{ page_obj.previous_page_number }}">
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" disabled href="#"
                tabindex="-1">
            {% endif %}
                Предыдущая</a>
            </li>
            {% for count in page_obj.paginator.page_range %}
            {% if products.number == count %}
            <li class="page-item active">
            {% elif count >= products.number|add:-2 and count <= products.number|add:2  %}
            <li class="page-item">
            {% endif %}
                <a class="page-link" href="?page={{ count }}">
                    {{ count }}
                </a>
            </li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                href="?page={{ page_obj.next_page_number }}">
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" disabled href="#"
                tabindex="-1">
            {% endif %}
                Следующая</a>
            </li>
        </ul>
    </nav>
{% endif %}

        </div>

    </div>

</div>
{% endblock %}


{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
</footer>
{% endblock %}